export const CART_ACTION_TYPES = {
  SET_CART_STATUS: "cart/SET_CART_STATUS",
  ADD_ITEM_TO_CART: "cart/ADD_ITEMS_TO_CART",
  REMOVE_ITEM_FROM_CART: "cart/REMOVE_ITEM_FROM_CART",
  INCREMENT_ITEM_QUANTITY: "cart/INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "cart/DECREMENT_ITEM_QUANTITY",
};